# Generated by Django 4.1 on 2024-01-31 05:37

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('userId', models.AutoField(default=None, primary_key=True, serialize=False)),
                ('username', models.CharField(max_length=100)),
                ('password', models.CharField(max_length=100)),
                ('email', models.CharField(max_length=100)),
                ('department', models.CharField(max_length=100)),
                ('contact', models.IntegerField()),
                ('role', models.CharField(choices=[('Admin', 'Admin'), ('Visitor', 'Visitor')], default='Visitor', max_length=10)),
            ],
        ),
    ]
